### PR TITLE
I updated the iRevealLite Installation Guide

### PR DESCRIPTION
**Pull request by fsoepyan**
- I added a few more details to the installation guide to help the user during the installation process
- I used Microsoft Word, with Track Changes

### CODE REVIEW

**Comment by ksbeattie** [comment]
I'm adding @jinliangma as a reviewer for this.  But why a new file?  Shouldn't this just be a new version of the existing one?

**Comment by ksbeattie** [comment]
Does this address some of #20 ?

**Comment by fsoepyan** [comment]
We can delete the old file, if it is no longer needed.

By the way, Keith (@ksbeattie), if possible, can you please allow me to assign reviewers, assignees, and labels for the iRevealLite repo? At the moment, I cannot do any of that.

**Comment by fsoepyan** [comment]
This PR does not address Issue #20, as I added Issue #20 after the installation of iRevealLite.

As I mentioned, the installation was successful.

**Comment by ksbeattie** [comment]
@fsoepyan, it's the new name of the file that is the problem.  You're updating the file, there's no need to create a new name for it.  Just update the existing one.  git (as well as track changes within the doc) will keep track of versioning for it, so there's no need for a timestamp in the name of the file.

I'd still like a review of the changes to this doc from @jinliangma, if that's possible.

@fsoepyan, check your perms now, I added read perms for the everyone team, though I'm not sure if that will be enough.

**Comment by jinliangma** [comment]
I've just realized that the "Release" and "Debug" selections for building the executable version is in the user's option file (*.suo) of VS which is not included in the GitHub repository.  The default selection is "Debug" if no *.suo file is found.  Therefore, in the installation guide, we need to ask the user to select the "Release" option before building the iRevealLite.exe file through VS.

**Pull request merged**
